"""
EWSB Mechanism Analysis — Bottleneck 3 root-cause investigation (Cycle 132).

PHYSICAL QUESTION:
  The electroweak VEV v = 246 GeV requires a Higgs mass parameter
  α_D6 = β v² / 2 ≈ 1070 GeV² in the DFC potential V(ε) = -α_D6/2 ε² + β/4 ε⁴.
  What DFC mechanism produces α_D6 ≈ 1070 GeV² when the natural D6 scale is
  M_c(D6) ≈ 9.70×10¹² GeV?

THE HIERARCHY IN DFC LANGUAGE:
  α_D6^required   ≈  1070 GeV²
  α_D6^natural    =  2 M_c(D6)²  ≈  1.88×10²⁶ GeV²   [D6 closure condition]
  Suppression needed:  α_D6^req / α_D6^nat  ≈  5.7×10⁻²⁴

  Equivalently, the EW VEV is suppressed relative to the D6 closure scale:
    v / M_c(D6)  =  246 / 9.70×10¹²  ≈  2.54×10⁻¹¹
    Δ_EW = log(M_c(D6) / v)  ≈  24.9  [24.9 e-folds between D6 and EW scale]

  This is the quantitative form of the DFC hierarchy problem.

ROUTE ANALYSIS (why standard mechanisms fail):

  Route A — "Natural" DFC VEV from D6 compression:
    If α_D6 = 2 M_c(D6)² (the D6 closure condition, analogous to D5), then:
      v_natural = 2 M_c(D6) / √β ≈ 1.03×10¹⁴ GeV   [4×10¹¹ too large]
    The D6 substrate potential would give EWSB at a scale ~10¹³ GeV, not 246 GeV.
    This IS the hierarchy problem in DFC language.

  Route B — SM RGE-driven EWSB (radiative):
    DFC provides λ_BC = β/4 ≈ 0.0088 at M_c(D6) with NO tree-level α_D6.
    Running SM RGE downward from M_c: λ INCREASES (Δλ ≈ +0.116 from two-loop SM).
    The Higgs quartic never reaches zero → NO RGE-driven EWSB.
    DFC STABILIZES the SM vacuum rather than breaking it dynamically.
    This route REQUIRES an explicit α_D6 term — it cannot be avoided.
    [This is why vev_derivation.py needs α_D6 as an external input.]

  Route C — D6/D7 classical overlap (I_D67, d6_d7_overlap.py):
    I_D67 = α_D6 / α_D7 = 1070 / (2 × M_c(D7)²) ≈ 2.18×10⁻²⁸
    Simple sech² profile overlap gives I_sech ≈ 0.006 — gap 2.8×10²⁵.
    All four candidate routes blocked (Cycle 131).
    This route identifies the gap but does not resolve it.

  Route D — Dimensional transmutation from D7 (analogy to QCD):
    If D7 induces a condensate at scale Λ_DFC ~ M_c(D7) × exp(-π/g_eff²):
      exp(-π/(8/27)) = exp(-π × 27/8) = exp(-10.6) ≈ 2.5×10⁻⁵
      Λ_DFC ~ 1.57×10¹⁵ × 2.5×10⁻⁵ ≈ 3.9×10¹⁰ GeV   [still too large by 10⁸]
    Would need exp(-Δ_EW) = v/M_c(D7) ≈ 1.57×10⁻¹³ — requires Δ_EW/π ≈ 9.4 in the exponent.
    No clean DFC combination gives this exponent from first principles.

  Route E — Power law in scale ratio:
    α_D6 = M_c(D6)² × (M_c(D6)/M_c(D7))^p × g(β)
    For p = 0: α_D6 = M_c(D6)² × g(β) = M_c(D6)² × β/2 ≈ 3.3×10²⁴ GeV²  [too large]
    For p = 2: α_D6 = M_c(D6)² × exp(-2 × 5.085) × β/2 ≈ 1.2×10¹⁵ GeV²  [too large]
    For p = 23: would give correct α_D6 — clearly unphysical.
    Power-law routes uniformly fail.

POSITIVE FINDING — SOFT MASS ANALOGY:
  The suppression (v/M_c(D6))² ≈ 6.4×10⁻²² has a natural DFC interpretation
  if the mass term α_D6 is NOT generated by D7 pressure but is instead a
  "soft mass" inherited from the depth-running:

    α_D6^soft = M_Pl² × (1 - γ_Higgs)^{N_Higgs}

  where γ_Higgs is a depth-running factor for the Higgs sector (different from
  γ_space which controls the closure scale sequence).

  For this to give α_D6 = 1070 GeV²:
    (1 - γ_Higgs)^N_Higgs = 1070 / M_Pl² = 1070 / (1.49×10³⁸) = 7.18×10⁻³⁶

  For N_Higgs = N_space = 5 (D1 to D6):
    (1 - γ_Higgs) = (7.18×10⁻³⁶)^(1/5) = 1.48×10⁻⁷

  Compare γ_space: from depth-running, (1-γ_space) ≈ 9×10⁻³  [controls M_c(D6)/M_Pl]

  The ratio: γ_Higgs / γ_space ≈ 1.48×10⁻⁷ / 9×10⁻³ ≈ 1.6×10⁻⁵

  In other words: γ_Higgs ~ γ_space² × (γ_space/something).

  If γ_Higgs = γ_space² (quadratic suppression of Higgs depth-running vs. gauge):
    (1 - γ_Higgs) ≈ 1 - (9×10⁻³)² ≈ 1 - 8.1×10⁻⁵ → (1-γ_Higgs)^5 ≈ 1 - 4×10⁻⁴
    That gives no suppression.

  If γ_Higgs = γ_space × β (quadratic-in-β suppression):
    (1 - γ_Higgs) ≈ 1 - 9×10⁻³ × 0.035 ≈ 1 - 3.2×10⁻⁴
    (1-γ_Higgs)^5 ≈ 0.9984 → nearly no suppression.

  CONCLUSION: Simple modifications of γ_space do not produce the required γ_Higgs.
  The soft mass route requires a QUALITATIVELY DIFFERENT mechanism for the Higgs
  sector depth-running, not just a rescaled version of the closure-scale running.

REVISED OPEN PROBLEM (Bottleneck 3):
  The Higgs mass parameter α_D6 ≈ 1070 GeV² requires:
    α_D6 / M_c(D6)²  ≈  5.7×10⁻²⁴  [24 orders below D6 natural scale]

  Three candidate DFC mechanisms remain:

  (i) CLASSICAL + RG: The tree-level α_D6 is generated by D7 pressure (classical
      overlap), and is then ENHANCED by RGE running from M_c down to v. The classical
      piece must still give ~1070 GeV². This reduces to the I_D67 gap (blocked, Cycle 131).

  (ii) KOIDE-TYPE SOFT MASS: The Z₃ D7 kink structure (Koide, Cycles 122-127)
      generates a small soft mass for the D6 squashing mode through the same
      mechanism that gives the lepton mass hierarchy. The DFC Yukawa t² = 1/Q_top
      (Cycle 126) might connect to the Higgs soft mass.
      CHECK: t² = 1/Q_top = 1/2. If α_D6 ~ t² × M_c(D6)² = M_c(D6)²/2, that's
      still α_D6 ~ 10²⁵ GeV² (no help). The Koide parameter gives O(1) suppression,
      not the 10²⁴ needed.

  (iii) NON-PERTURBATIVE D6 CONDENSATE: Analogous to QCD chiral condensate,
      a D6 non-perturbative effect generates:
        α_D6^NP ~ M_c(D6)² × exp(-c/g_D6²)
      where g_D6 is the D6 coupling and c is a numerical coefficient.
      For α_D6^NP = 1070 GeV²:
        exp(-c/g_eff²) = 1070/M_c(D6)² = 5.7×10⁻²⁴
        c/g_eff² = 53.8
        c = 53.8 × g_eff² = 53.8 × 8/27 = 15.9
      c = 16 is close to 16π² (one-loop factor). If c = π²:
        π²/(g_eff²) = π² × 27/8 = 33.2 → exp(-33.2) ≈ 2.7×10⁻¹⁵
        α_D6^NP ~ M_c(D6)² × 2.7×10⁻¹⁵ ≈ 5.1×10¹¹ GeV²  [still too large by 5×10⁸]
      For c = 2π²:
        2π²/(g_eff²) = 66.5 → exp(-66.5) ≈ 7.2×10⁻³⁰
        α_D6^NP ~ M_c(D6)² × 7.2×10⁻³⁰ ≈ 1.36×10⁻⁴ GeV²  [too small by 10⁷]
      The non-perturbative route brackets the target but cannot hit it exactly
      without deriving c from the D6 substrate dynamics.

ASSESSMENT:
  All three routes partially work but none closes the gap from first principles.
  The hierarchy v << M_c(D6) remains the central open problem of DFC.
  This IS the hierarchy problem in DFC language, and it requires the same
  depth of new insight that the SM hierarchy problem requires.

KEY REFERENCES:
  - equations/d6_d7_overlap.py       (Cycle 131: I_D67 gap = 2.8×10²⁵)
  - equations/vev_derivation.py      (Cycle 86: λ_BC=β/4, SM RGE, μ=23 GeV target)
  - foundations/vev_derivation.md    (Cycle 131: ECCC + gap analysis)
  - foundations/hierarchy_problem.md (structural hierarchy dissolution argument)
  - equations/mc_closure_scales.py   (Cycle 130: M_c(D6)=9.70e12, M_c(D7)=1.57e15)
  - equations/koide_complex_circulant.py (Cycle 126: t²=1/Q_top from Koide chain)

Usage:
    python3 equations/ewsb_mechanism.py
"""

import math

# ── DFC Parameters ────────────────────────────────────────────────────────────

BETA         = 1.0 / (9.0 * math.pi)    # β = 1/(9π) [Tier 2a, Cycle 117]
G_EFF_SQ     = 8.0 / 27.0               # g_eff² [Tier 2a, Cycle 117]
Q_TOP        = 2.0                       # topological charge [Tier 1, Cycle 111]
I4           = 4.0 / 3.0                # kink shape integral [Tier 1, Cycle 47]

# Scales
M_PLANCK     = 1.22e19    # GeV
M_C_D6       = 9.6978e12  # GeV  [ECCC, Cycle 130]
M_C_D7       = 1.5663e15  # GeV  [ECCC, Cycle 130]
DELTA_D67    = math.log(M_C_D7 / M_C_D6)   # = 5.085
V_EW         = 246.0      # GeV  [experimental target]
M_H_OBS      = 125.25     # GeV


def hierarchy_summary():
    """
    Compute and display the DFC hierarchy problem in quantitative terms.

    The electroweak VEV v = 246 GeV requires α_D6 = β v²/2 in V(ε) = -α_D6/2 ε² + β/4 ε⁴.
    The D6 closure scale sets a natural mass: α_D6^natural = 2 M_c(D6)².
    The ratio α_D6^req / α_D6^nat is the quantitative hierarchy problem.
    """
    # Required: from potential minimum with v = 246 GeV
    lam_dfc   = BETA / 4.0
    alpha_req = BETA * V_EW**2 / 2.0
    v_from_a  = math.sqrt(2 * alpha_req / BETA)   # = V_EW by construction

    # Natural: D6 closure condition α_D6 = 2 M_c(D6)²
    alpha_nat = 2.0 * M_C_D6**2
    v_natural = math.sqrt(2.0 * alpha_nat / BETA)  # what v would be if α_D6 = α_D6^natural

    # Hierarchy
    suppression    = alpha_req / alpha_nat
    ratio_v        = V_EW / v_natural
    delta_ew       = math.log(M_C_D6 / V_EW)     # log(M_c(D6)/v)
    delta_planck   = math.log(M_PLANCK / V_EW)   # log(M_Pl/v)

    return {
        'lambda_dfc':      lam_dfc,
        'alpha_req':       alpha_req,
        'alpha_natural':   alpha_nat,
        'v_natural_GeV':   v_natural,
        'suppression':     suppression,
        'ratio_v':         ratio_v,
        'delta_ew':        delta_ew,
        'delta_planck':    delta_planck,
    }


def rge_ewsb_check():
    """
    Check whether SM RGE running from M_c(D6) to low energies drives EWSB.

    DFC provides λ_BC = β/4 > 0 at M_c with NO tree-level mass term.
    Running SM Higgs quartic from M_c downward:
      - If λ(v) > 0 throughout: EWSB requires an explicit α_D6 input (hierarchy problem)
      - If λ hits zero: EWSB via radiative CW mechanism (no explicit α_D6 needed)

    One-loop beta function for λ (top Yukawa dominated):
      dλ/dt = [24λ² + 12 y_t² λ - 6 y_t⁴ - ...] / (16π²)
      At small λ, dominated by: dλ/dt ≈ (-6 y_t⁴ + 12 y_t² λ) / (16π²)
    """
    # Use simplified one-loop estimate: only top Yukawa + Higgs quartic
    # y_t at M_c(D6) from SM running (approximate: y_t decreases slowly)
    # y_t(M_Z) ≈ 0.994; rough estimate at M_c(D6) ~ 10^13 GeV:
    # one-loop Yukawa running: dy_t/dt = y_t/(16π²) × (9/2 y_t² - 8 g_3² ...)
    # g_3 at M_c(D6) ~ g_eff ~ 0.544 (ECCC), so 8 g_3² ~ 8 × 0.296 ~ 2.37
    # dy_t²/dt ≈ y_t²/(8π²) × (9/2 × y_t² - 8 × 0.296)
    # At M_c: y_t ≈ 0.4 (rough from running over ~11 decades)

    y_t_mc = 0.40    # approximate top Yukawa at M_c(D6) [from SM RGE, rough estimate]
    lam_bc = BETA / 4.0

    # One-loop running from M_c down to scale μ: dλ/d(ln μ) = β_λ/t where t = ln(μ/M_Z)
    # Since we run DOWN (μ decreasing), t decreases, so dλ/dμ ∝ -β_λ
    # β_λ ≈ (12 y_t² λ - 6 y_t⁴) / (16π²) at small λ

    def dlam_dt(lam, yt):
        """One-loop beta function for Higgs quartic (simplified, dominant terms)."""
        return (24.0 * lam**2 + 12.0 * yt**2 * lam - 6.0 * yt**4) / (16.0 * math.pi**2)

    # Integrate from M_c down to M_Z in steps
    t_mc = math.log(M_C_D6 / 91.19)   # ln(M_c/M_Z)
    t_mz = 0.0
    n_steps = 5000
    dt = (t_mz - t_mc) / n_steps

    lam = lam_bc
    yt  = y_t_mc
    t   = t_mc
    lam_zero_scale = None

    for _ in range(n_steps):
        lam_prev = lam
        lam += dlam_dt(lam, yt) * dt
        t   += dt
        mu   = 91.19 * math.exp(t)
        if lam_prev > 0 and lam < 0 and lam_zero_scale is None:
            lam_zero_scale = mu

    lam_at_mz = lam

    return {
        'lam_bc':            lam_bc,
        'y_t_mc':            y_t_mc,
        'lam_at_mz':         lam_at_mz,
        'lam_zero_scale':    lam_zero_scale,    # None if λ stays positive
        'ewsb_radiative':    lam_zero_scale is not None,
    }


def soft_mass_route(n_steps=5):
    """
    Explore the 'soft mass' depth-running route for generating α_D6.

    If the Higgs mass parameter α_D6 is generated by depth-running analogously
    to the closure scale running:
      α_D6^soft = M_Pl² × (1 - γ_Higgs)^N

    Find γ_Higgs that gives α_D6^soft = β v²/2 after N depth steps (D1→D6).

    Also compute γ_space from M_c(D6)/M_Pl and compare.
    """
    alpha_req = BETA * V_EW**2 / 2.0

    # γ_Higgs needed
    ratio = alpha_req / M_PLANCK**2
    gamma_higgs_minus1 = ratio**(1.0 / n_steps)
    gamma_higgs = 1.0 - gamma_higgs_minus1

    # γ_space from depth-running: M_c(D6) = M_Pl × (1 - γ_space)^(N/2)
    # → (1 - γ_space) = (M_c(D6)/M_Pl)^(2/N)
    gamma_space_minus1 = (M_C_D6 / M_PLANCK)**(2.0 / n_steps)
    gamma_space = 1.0 - gamma_space_minus1

    return {
        'n_steps':           n_steps,
        'alpha_req':         alpha_req,
        'gamma_higgs':       gamma_higgs,
        'gamma_space':       gamma_space,
        'ratio_gammas':      gamma_higgs / gamma_space,
        'gamma_higgs_approx': gamma_space**2,    # if γ_Higgs ~ γ_space²
        'alpha_from_gamma2': M_PLANCK**2 * (1 - gamma_space**2)**n_steps,
    }


def nonperturbative_route():
    """
    Non-perturbative condensate route for α_D6.

    Analogy to QCD: the D6 gauge dynamics generate a condensate at scale:
      α_D6^NP = M_c(D6)² × exp(-c / g_eff²)

    Find c that gives α_D6^NP = β v²/2.
    Compare c to natural DFC values (π², 2π², N_Hopf π, etc.).
    """
    alpha_req = BETA * V_EW**2 / 2.0
    alpha_nat = M_C_D6**2   # natural scale (one factor, not two)

    # Solve: alpha_nat × exp(-c/g_eff²) = alpha_req
    # → exp(-c/g_eff²) = alpha_req/alpha_nat
    # → c = -g_eff² × log(alpha_req/alpha_nat)

    ratio = alpha_req / alpha_nat
    c     = -G_EFF_SQ * math.log(ratio)

    # Compare to natural DFC combinations
    c_candidates = {
        'π²':            math.pi**2,
        '2π²':           2 * math.pi**2,
        'N_Hopf × π':   9 * math.pi,
        '2π/β':          2 * math.pi / BETA,
        'π²/β':          math.pi**2 / BETA,
        '8π²':           8 * math.pi**2,
        '16π²':          16 * math.pi**2,
    }

    return {
        'alpha_req':     alpha_req,
        'alpha_nat':     alpha_nat,
        'c_needed':      c,
        'c_candidates':  c_candidates,
        'alpha_from_candidates': {
            name: alpha_nat * math.exp(-val / G_EFF_SQ)
            for name, val in c_candidates.items()
        },
    }


def power_law_route():
    """
    Power-law route: α_D6 = M_c(D6)² × (M_c(D6)/M_c(D7))^p × prefactor.

    Find p and the required prefactor.
    Compare to integer/half-integer values.
    """
    alpha_req = BETA * V_EW**2 / 2.0
    ratio_scales = M_C_D6 / M_C_D7   # = exp(-Δ_D67) ≈ 0.00619

    results = []
    for p in [1, 2, 3, 4, 5, 6, 8, 10, 12]:
        alpha_p = M_C_D6**2 * ratio_scales**p
        prefactor_needed = alpha_req / alpha_p
        results.append({
            'p':               p,
            'alpha_p':         alpha_p,
            'prefactor_needed': prefactor_needed,
            'log10_ratio':     math.log10(alpha_p / alpha_req),
        })

    # Find exact p
    p_exact = math.log(alpha_req / M_C_D6**2) / math.log(ratio_scales)

    return {
        'alpha_req':  alpha_req,
        'results':    results,
        'p_exact':    p_exact,
        'delta_d67':  DELTA_D67,
    }


# ── Main Output ───────────────────────────────────────────────────────────────

if __name__ == '__main__':
    print('=' * 70)
    print('EWSB MECHANISM ANALYSIS — BOTTLENECK 3 ROOT-CAUSE (Cycle 132)')
    print('Dimensional Folding Compression model')
    print('=' * 70)

    # ─── A: Hierarchy summary ─────────────────────────────────────────────────
    h = hierarchy_summary()
    print('\n[A] DFC HIERARCHY PROBLEM — QUANTITATIVE')
    print(f'  β = 1/(9π)             = {BETA:.6f}   [Tier 2a, Cycle 117]')
    print(f'  λ_DFC = β/4            = {h["lambda_dfc"]:.6f}')
    print(f'  M_c(D6)                = {M_C_D6:.4e} GeV   [ECCC, Cycle 130]')
    print()
    print(f'  Required (to give v=246 GeV):')
    print(f'    α_D6^req = β v²/2    = {h["alpha_req"]:.4e} GeV²')
    print()
    print(f'  Natural (from D6 closure: α_D6 = 2 M_c(D6)²):')
    print(f'    α_D6^nat = 2 M_c(D6)² = {h["alpha_natural"]:.4e} GeV²')
    print(f'    v_natural = 2 M_c(D6)/√β = {h["v_natural_GeV"]:.4e} GeV')
    print()
    print(f'  HIERARCHY RATIO:')
    print(f'    α_D6^req / α_D6^nat  = {h["suppression"]:.3e}   ({math.log10(h["suppression"]):.1f} orders)')
    print(f'    v / v_natural        = {h["ratio_v"]:.3e}   ({math.log10(h["ratio_v"]):.1f} orders)')
    print(f'    Δ_EW = log(M_c/v)    = {h["delta_ew"]:.3f}   [EW/D6 log-separation]')
    print(f'    exp(-2 Δ_EW)         = {math.exp(-2*h["delta_ew"]):.3e}   [required suppression of α_D6/M_c(D6)²]')
    print(f'    Δ_Pl = log(M_Pl/v)   = {h["delta_planck"]:.3f}   [EW/Planck log-separation, for context]')

    # ─── B: RGE EWSB check ────────────────────────────────────────────────────
    rge = rge_ewsb_check()
    print(f'\n[B] SM RGE: DOES DFC GET EWSB WITHOUT EXPLICIT α_D6?')
    print(f'  λ_BC = β/4             = {rge["lam_bc"]:.6f}   [DFC UV boundary condition at M_c(D6)]')
    print(f'  y_t at M_c(D6) (approx) = {rge["y_t_mc"]:.3f}   [from rough SM one-loop running]')
    print(f'  Running DFC λ from M_c DOWN to M_Z (one-loop simplified):')
    print(f'  λ at M_Z               = {rge["lam_at_mz"]:+.5f}')
    if rge['ewsb_radiative']:
        print(f'  λ crosses zero at      ~ {rge["lam_zero_scale"]:.3e} GeV  → RADIATIVE EWSB possible')
    else:
        print(f'  λ does NOT cross zero in running M_c → M_Z')
        print(f'  → NO radiative EWSB in DFC (λ stays positive)')
        print(f'  → DFC REQUIRES an explicit α_D6 ≈ {h["alpha_req"]:.0f} GeV² from D6/D7 physics')
        print(f'  → The hierarchy problem is NOT resolved by RGE alone')

    # ─── C: Soft mass route ────────────────────────────────────────────────────
    sm = soft_mass_route()
    print(f'\n[C] SOFT MASS DEPTH-RUNNING ROUTE')
    print(f'  Hypothesis: α_D6 = M_Pl² × (1 - γ_Higgs)^{sm["n_steps"]}')
    print(f'  γ_Higgs needed         = {sm["gamma_higgs"]:.4e}')
    print(f'  γ_space (from M_c/M_Pl) = {sm["gamma_space"]:.4e}')
    print(f'  Ratio γ_Higgs/γ_space  = {sm["ratio_gammas"]:.3e}')
    print(f'  γ_Higgs ≈ γ_space²     = {sm["gamma_higgs_approx"]:.4e}   (test: quadratic hypothesis)')
    print(f'  α_D6 from γ_space² hyp = {sm["alpha_from_gamma2"]:.3e} GeV²   (vs. {h["alpha_req"]:.3e} needed)')
    print(f'  → Quadratic γ hypothesis fails by {sm["alpha_from_gamma2"]/h["alpha_req"]:.1e}×')
    print(f'  → No simple modification of γ_space produces the required γ_Higgs')

    # ─── D: Non-perturbative route ─────────────────────────────────────────────
    np_r = nonperturbative_route()
    print(f'\n[D] NON-PERTURBATIVE CONDENSATE ROUTE')
    print(f'  Hypothesis: α_D6^NP = M_c(D6)² × exp(-c/g_eff²)')
    print(f'  c needed               = {np_r["c_needed"]:.4f}')
    print(f'  g_eff²                 = {G_EFF_SQ:.6f}')
    print(f'  Natural DFC values of c:')
    for name, val in np_r['c_candidates'].items():
        alpha_c = np_r['alpha_from_candidates'][name]
        ratio_c = alpha_c / np_r['alpha_req']
        marker = ' ←  CLOSEST' if 0.001 < ratio_c < 1000 else ''
        print(f'    c = {name:12s} = {val:8.4f}:  α_D6 = {alpha_c:.2e} GeV²  '
              f'[ratio {ratio_c:.2e}]{marker}')

    # ─── E: Power-law route ────────────────────────────────────────────────────
    pl = power_law_route()
    print(f'\n[E] POWER-LAW ROUTE: α_D6 = M_c(D6)² × (M_c(D6)/M_c(D7))^p')
    print(f'  M_c(D6)/M_c(D7)        = exp(-Δ_D67) = {math.exp(-pl["delta_d67"]):.5f}')
    print(f'  Exact p needed         = {pl["p_exact"]:.3f}')
    print(f'  {'p':>4}  {'α_D6 (GeV²)':>16}  {'log10(ratio)':>13}')
    print(f'  {"-"*4}  {"-"*16}  {"-"*13}')
    for r in pl['results']:
        marker = ' ←' if abs(r['log10_ratio']) < 2 else ''
        print(f'  {r["p"]:4d}  {r["alpha_p"]:16.3e}  {r["log10_ratio"]:13.2f}{marker}')
    print(f'  → No integer p gives the right answer')
    print(f'  → p ≈ {pl["p_exact"]:.1f} is large and unnatural')

    # ─── F: Summary ────────────────────────────────────────────────────────────
    print(f'\n{"=" * 70}')
    print(f'SUMMARY: BOTTLENECK 3 ROOT-CAUSE ANALYSIS')
    print(f'{"=" * 70}')
    print(f'')
    print(f'  The DFC hierarchy problem: α_D6^req / α_D6^nat ≈ {h["suppression"]:.2e}')
    print(f'  This is ({V_EW:.0f} GeV / {h["v_natural_GeV"]:.2e} GeV)² = exp(-2 × {h["delta_ew"]:.1f}).')
    print(f'')
    print(f'  Route     Mechanism                     Gap to correct α_D6')
    print(f'  ───────────────────────────────────────────────────────────────')
    print(f'  A: Natural DFC (α=2M_c²)               {h["alpha_natural"]/h["alpha_req"]:.1e}× too large')
    if rge['ewsb_radiative']:
        print(f'  B: SM RGE EWSB                          Partially closes at ~{rge["lam_zero_scale"]:.2e} GeV')
    else:
        print(f'  B: SM RGE EWSB                          FAILS — λ stays positive, no CW minimum')
    print(f'  C: D6/D7 classical overlap (I_D67)      2.8×10²⁵ gap (Cycle 131)')
    print(f'  D: Dimensional transmutation            Brackets target but cannot fix exponent')
    print(f'  E: Power law (D6/D7 ratio)^p            p ≈ {pl["p_exact"]:.0f} required, unnatural')
    print(f'  F: NP condensate exp(-c/g²)             Requires c ≈ {np_r["c_needed"]:.1f}; no clean DFC value')
    print(f'')
    print(f'  OPEN PROBLEM (Tier 4):')
    print(f'  Derive α_D6 ≈ {h["alpha_req"]:.0f} GeV² from DFC substrate dynamics')
    print(f'  without fine-tuning. This is equivalent to deriving v = {V_EW:.0f} GeV.')
    print(f'')
    print(f'  MOST PROMISING CANDIDATE (Tier 4 exploration):')
    print(f'  Non-perturbative D6 condensate with c ≈ {np_r["c_needed"]:.1f}.')
    print(f'  The required c brackets π² ({math.pi**2:.2f}) and 2π² ({2*math.pi**2:.2f}),')
    print(f'  suggesting a one-loop-suppressed non-perturbative effect at the D6 scale.')
    print(f'  NEXT STEP: Identify the D6 field theory whose one-loop exact beta function')
    print(f'  gives the confinement scale v ~ M_c(D6) × exp(-c_D6/g_D6²).')
    print(f'')
    print(f'  TIER ASSIGNMENTS:')
    print(f'  α_D6^req = β v²/2 = {h["alpha_req"]:.0f} GeV²:  Tier 3 [β Tier 2a; v experimental]')
    print(f'  α_D6^nat = 2 M_c(D6)² = {h["alpha_natural"]:.2e} GeV²:  Tier 1 [D6 closure condition]')
    print(f'  Gap factor = {h["alpha_natural"]/h["alpha_req"]:.2e}:  Tier 4 OPEN [no DFC mechanism found]')
