"""
f_pi from Pagels-Stokar with Running Quark Mass
=================================================

Physical question:
    C387 computed f_pi = 89.63 MeV from the Pagels-Stokar formula with
    constant constituent mass M_q = M_N/3 and UV cutoff m_omega. This
    undershoots observed (92.07 MeV) by -2.7%. Meanwhile, Λ/π = 96.9 MeV
    overshoots by +5.3%. C421 showed the deuteron binding threshold is at
    f_pi < 96.5 MeV, with best match at ~94.5 MeV.

    The key missing physics: in QCD, the dynamical quark mass M(k) RUNS —
    falling from ~330 MeV at k=0 to ~few MeV at k >> Λ_QCD. The full
    Pagels-Stokar formula with running mass includes an enhancement factor
    [1 - k M'(k)/M(k)] that is > 1 when M decreases with k. This pushes
    f_pi UP from the constant-mass estimate.

DFC mechanism:
    The running mass M(k) is generated by dynamical chiral symmetry breaking
    at D7 depths. DFC provides the IR mass M_q = M_N/3, the chiral scale
    Λ_QCD, and the UV cutoff m_omega. The running profile M(k) between
    these scales is determined by the D7 gap equation.

Key references:
    - Pagels & Stokar (1979): Phys. Rev. D 20, 2947
    - Roberts & Williams (1994): Prog. Part. Nucl. Phys. 33, 477
    - Maris & Roberts (2003): Int. J. Mod. Phys. E 12, 297
    - equations/fpi_correction_t18.py (C387): constant-mass PS result
    - equations/nuclear_2pi_exchange.py (C420-C421): f_pi binding threshold
"""

import math

# =============================================================================
# Assertion infrastructure
# =============================================================================
n_assert = 0
n_pass = 0
n_fail = 0


def check(label, condition):
    global n_assert, n_pass, n_fail
    n_assert += 1
    ok = bool(condition)
    tag = "PASS" if ok else "FAIL"
    if not ok:
        n_fail += 1
    else:
        n_pass += 1
    print(f"  [{tag}] {label}")
    return ok


# =============================================================================
# DFC parameters
# =============================================================================
PI = math.pi
LAMBDA_QCD = 304.5       # MeV
N_C = 3

M_N = math.sqrt(3.0 * PI) * LAMBDA_QCD       # 934.8 MeV
M_OMEGA = math.sqrt(2.0 * PI) * LAMBDA_QCD   # 763.3 MeV
M_Q = M_N / 3.0                               # 311.6 MeV (constituent)

F_PI_OBS = 92.07  # MeV
F_PI_DFC = LAMBDA_QCD / PI  # 96.9 MeV
F_PI_PS_CONST = 89.63  # MeV (C387 result, constant mass)

# UV cutoff for PS integral
LAMBDA_UV = M_OMEGA  # 763.3 MeV


# =============================================================================
# Part A: Reproduce constant-mass PS result (verification)
# =============================================================================
print("=" * 72)
print("Part A: Verify constant-mass Pagels-Stokar (C387)")
print("=" * 72)
print()

# Constant-mass PS: f_pi^2 = (N_c/(4*pi^2)) * M_q^2 * [ln(1+x) - x/(1+x)]
# where x = Lambda_UV^2 / M_q^2
x0 = LAMBDA_UV**2 / M_Q**2
I_const = math.log(1.0 + x0) - x0 / (1.0 + x0)
f2_const = (N_C / (4.0 * PI**2)) * M_Q**2 * I_const
fpi_const = math.sqrt(f2_const)

print(f"  M_q = M_N/3 = {M_Q:.1f} MeV")
print(f"  Lambda_UV = m_omega = {LAMBDA_UV:.1f} MeV")
print(f"  m_omega/M_q = sqrt(6) = {LAMBDA_UV/M_Q:.6f}")
print(f"  I = ln(7) - 6/7 = {I_const:.6f}")
print(f"  f_pi(const) = {fpi_const:.2f} MeV ({(fpi_const/F_PI_OBS-1)*100:+.1f}%)")
print()

check("A1: reproduces C387 constant-mass result",
      abs(fpi_const - F_PI_PS_CONST) < 0.1)
print()


# =============================================================================
# Part B: Running mass models
# =============================================================================
print("=" * 72)
print("Part B: Running quark mass models")
print("=" * 72)
print()

# The full PS formula with running mass M(k):
#   f_pi^2 = (N_c/(4*pi^2)) * int_0^{Lambda^2} dk^2
#            * M(k)^2 / (k^2 + M(k)^2)^2
#            * [1 - k^2 * M'(k^2) / M(k)]
#
# For constant M: the bracket = 1, recovering the standard result.
# For falling M: M'(k^2) < 0, so the bracket > 1 (ENHANCEMENT).

# Model 1: Power-law running (Cornwall/Roberts form)
#   M(k^2) = M_q * [Lambda_chi^2 / (k^2 + Lambda_chi^2)]^gamma
#   where Lambda_chi = chiral scale, gamma = mass anomalous dimension

# Model 2: Gaussian running (lattice-inspired)
#   M(k^2) = M_q * exp(-k^2 / (2*Lambda_chi^2))

# Model 3: Step function (NJL limit)
#   M(k^2) = M_q * theta(Lambda^2 - k^2)
#   This is the constant-mass case up to Lambda, then zero.


def ps_running(M_func, dM_dk2_func, Lambda_UV_val, n_pts=2000):
    """
    Full Pagels-Stokar integral with running mass.
    M_func(k2): mass as function of k^2 (MeV^2)
    dM_dk2_func(k2): dM/d(k^2)
    Returns f_pi^2 in MeV^2.
    """
    dk2 = Lambda_UV_val**2 / n_pts
    integral = 0.0
    for i in range(n_pts + 1):
        k2 = i * dk2
        M = M_func(k2)
        dM = dM_dk2_func(k2)
        denom = (k2 + M**2)**2
        if denom < 1e-30:
            continue
        # The PS enhancement factor: 1 - k^2 * (dM/dk^2) / M
        # Note: dM/dk^2 is dM/d(k^2), not dM/dk
        if abs(M) < 1e-10:
            bracket = 1.0
        else:
            bracket = 1.0 - k2 * dM / M
        integrand = k2 * M**2 / denom * bracket

        # Simpson's rule weight
        w = 1.0 if (i == 0 or i == n_pts) else (4.0 if i % 2 == 1 else 2.0)
        integral += w * integrand

    integral *= dk2 / 3.0
    f2 = (N_C / (4.0 * PI**2)) * integral
    return f2


# --- Model 1: Power-law running ---
print("Model 1: Power-law running M(k²) = M_q × [Λ²_χ/(k²+Λ²_χ)]^γ")
print()

for gamma in [0.5, 0.75, 1.0, 1.25, 1.5]:
    Lambda_chi = LAMBDA_QCD

    def M_power(k2, g=gamma, L=Lambda_chi):
        return M_Q * (L**2 / (k2 + L**2))**g

    def dM_power(k2, g=gamma, L=Lambda_chi):
        # dM/d(k²) = M_q * g * L^{2g} * (-1) * (k² + L²)^{-(g+1)}
        return M_Q * g * L**(2*g) * (-1.0) * (k2 + L**2)**(-(g+1))

    f2 = ps_running(M_power, dM_power, LAMBDA_UV)
    fpi = math.sqrt(max(f2, 0))
    err = (fpi / F_PI_OBS - 1) * 100
    enhancement = fpi / fpi_const
    print(f"  γ = {gamma:.2f}: f_pi = {fpi:.2f} MeV ({err:+.1f}%), "
          f"enhancement = {enhancement:.3f}x vs constant")

print()

# --- Model 2: Power-law with Lambda_chi = Lambda_QCD/sqrt(2) ---
print("Model 1b: Power-law with Λ_χ = Λ_QCD/√2 (softer running)")
print()

for gamma in [0.5, 0.75, 1.0, 1.25]:
    Lambda_chi = LAMBDA_QCD / math.sqrt(2)

    def M_power2(k2, g=gamma, L=Lambda_chi):
        return M_Q * (L**2 / (k2 + L**2))**g

    def dM_power2(k2, g=gamma, L=Lambda_chi):
        return M_Q * g * L**(2*g) * (-1.0) * (k2 + L**2)**(-(g+1))

    f2 = ps_running(M_power2, dM_power2, LAMBDA_UV)
    fpi = math.sqrt(max(f2, 0))
    err = (fpi / F_PI_OBS - 1) * 100
    print(f"  γ = {gamma:.2f}: f_pi = {fpi:.2f} MeV ({err:+.1f}%)")

print()

# --- Model 3: Gaussian running ---
print("Model 2: Gaussian running M(k²) = M_q × exp(-k²/(2Λ²_χ))")
print()

for Lambda_chi in [LAMBDA_QCD, LAMBDA_QCD * 1.5, M_Q, M_OMEGA / 2]:
    def M_gauss(k2, L=Lambda_chi):
        return M_Q * math.exp(-k2 / (2.0 * L**2))

    def dM_gauss(k2, L=Lambda_chi):
        return M_Q * (-1.0 / (2.0 * L**2)) * math.exp(-k2 / (2.0 * L**2))

    f2 = ps_running(M_gauss, dM_gauss, LAMBDA_UV)
    fpi = math.sqrt(max(f2, 0))
    err = (fpi / F_PI_OBS - 1) * 100
    print(f"  Λ_χ = {Lambda_chi:.1f} MeV: f_pi = {fpi:.2f} MeV ({err:+.1f}%)")

print()


# =============================================================================
# Part C: Best DFC-motivated running mass
# =============================================================================
print("=" * 72)
print("Part C: DFC-motivated running mass selection")
print("=" * 72)
print()

# In QCD, the mass anomalous dimension gamma_m ≈ 12/(33-2*N_f) at one loop
# For N_f = 3 (light flavors): gamma_m = 12/27 = 4/9 ≈ 0.44
# In DFC: b_0 = 11, so gamma_m = 12/(2*b_0) = 12/22 = 6/11 ≈ 0.545
# (pure gauge b_0 = 11, with N_f quarks: b_0 = 11 - 2*N_f/3)

gamma_qcd_nf3 = 12.0 / 27.0  # 0.444
gamma_dfc_pure = 6.0 / 11.0   # 0.545
gamma_qcd_nf0 = 12.0 / 22.0   # same as DFC pure gauge

print(f"  Mass anomalous dimension (one-loop):")
print(f"    QCD (N_f=3):    γ_m = 12/27 = {gamma_qcd_nf3:.4f}")
print(f"    QCD (N_f=0):    γ_m = 12/22 = {gamma_qcd_nf0:.4f}")
print(f"    DFC (b₀=11):    γ_m = 6/11  = {gamma_dfc_pure:.4f}")
print()

# The DFC-motivated choice:
# - gamma = 6/11 (from DFC b_0 = 11)
# - Lambda_chi = Lambda_QCD (the chiral/confinement scale)
# - M_q = M_N/3 (DFC constituent mass)
# - Lambda_UV = m_omega (DFC UV cutoff)

gamma_dfc = 6.0 / 11.0
Lambda_chi_dfc = LAMBDA_QCD

print(f"  DFC running mass model (0 free parameters):")
print(f"    M(k²) = M_q × [Λ²_QCD / (k² + Λ²_QCD)]^(6/11)")
print(f"    M_q = M_N/3 = {M_Q:.1f} MeV")
print(f"    Λ_χ = Λ_QCD = {LAMBDA_QCD:.1f} MeV")
print(f"    Λ_UV = m_ω = {LAMBDA_UV:.1f} MeV")
print(f"    γ = 6/b₀ = 6/11 = {gamma_dfc:.6f}")
print()


def M_dfc(k2):
    return M_Q * (Lambda_chi_dfc**2 / (k2 + Lambda_chi_dfc**2))**gamma_dfc


def dM_dfc(k2):
    return (M_Q * gamma_dfc * Lambda_chi_dfc**(2*gamma_dfc)
            * (-1.0) * (k2 + Lambda_chi_dfc**2)**(-(gamma_dfc+1)))


f2_dfc = ps_running(M_dfc, dM_dfc, LAMBDA_UV)
fpi_dfc_running = math.sqrt(f2_dfc)
err_dfc = (fpi_dfc_running / F_PI_OBS - 1) * 100
enhancement_dfc = fpi_dfc_running / fpi_const

print(f"  RESULT:")
print(f"    f_pi(DFC running) = {fpi_dfc_running:.2f} MeV ({err_dfc:+.1f}%)")
print(f"    Enhancement over constant-mass: {enhancement_dfc:.3f}x")
print(f"    f_pi(constant)    = {fpi_const:.2f} MeV ({(fpi_const/F_PI_OBS-1)*100:+.1f}%)")
print(f"    f_pi(Λ/π)         = {F_PI_DFC:.2f} MeV ({(F_PI_DFC/F_PI_OBS-1)*100:+.1f}%)")
print(f"    f_pi(observed)    = {F_PI_OBS:.2f} MeV")
print()

check("C1: running mass enhances f_pi vs constant", fpi_dfc_running > fpi_const)
check("C2: running mass closer to observed than constant",
      abs(fpi_dfc_running/F_PI_OBS - 1) < abs(fpi_const/F_PI_OBS - 1))
check("C3: running mass closer to observed than Λ/π",
      abs(fpi_dfc_running/F_PI_OBS - 1) < abs(F_PI_DFC/F_PI_OBS - 1))
print()

# Print the running mass profile
print("  Running mass profile M(k):")
print(f"  {'k (MeV)':>10s}  {'M(k) (MeV)':>12s}  {'M/M_q':>8s}  {'bracket':>8s}")
print("  " + "-" * 44)
for k_val in [0, 50, 100, 150, 200, 250, 300, 400, 500, 600, 763]:
    k2 = k_val**2.0
    M_val = M_dfc(k2)
    dM_val = dM_dfc(k2)
    bracket = 1.0 - k2 * dM_val / M_val if abs(M_val) > 1e-10 else 1.0
    print(f"  {k_val:>10.0f}  {M_val:>12.1f}  {M_val/M_Q:>8.3f}  {bracket:>8.3f}")
print()


# =============================================================================
# Part D: Connection to deuteron binding
# =============================================================================
print("=" * 72)
print("Part D: Connection to deuteron binding (C421)")
print("=" * 72)
print()

# From C421: binding threshold at f_pi < 96.5 MeV
F_PI_THRESHOLD = 96.5  # MeV

print(f"  Deuteron binding threshold (C421): f_pi < {F_PI_THRESHOLD:.1f} MeV")
print()
print(f"  f_pi estimates vs threshold:")
print(f"  {'Method':<40s}  {'f_pi':>8s}  {'vs threshold':>14s}  {'vs obs':>8s}")
print("  " + "-" * 74)

results = [
    ("Λ/π (crude)", F_PI_DFC),
    ("Pagels-Stokar (constant M_q)", fpi_const),
    (f"PS + running mass (γ=6/11)", fpi_dfc_running),
    ("Observed", F_PI_OBS),
]

for label, fpi in results:
    margin = fpi - F_PI_THRESHOLD
    err = (fpi / F_PI_OBS - 1) * 100
    bound = "BINDS" if fpi < F_PI_THRESHOLD else "NOT BOUND"
    print(f"  {label:<40s}  {fpi:>7.2f}  {margin:>+6.1f} MeV ({bound})  {err:>+6.1f}%")

print()

if fpi_dfc_running < F_PI_THRESHOLD:
    print(f"  DEUTERON BINDS with DFC running-mass f_pi!")
    print(f"  Margin: {F_PI_THRESHOLD - fpi_dfc_running:.1f} MeV below threshold")
else:
    print(f"  Still {fpi_dfc_running - F_PI_THRESHOLD:.1f} MeV above binding threshold.")
    print(f"  Need additional corrections or slightly different gamma.")
print()

# What gamma gives f_pi = observed?
print("  Gamma scan — what γ matches observed f_pi?")
print(f"  {'γ':>6s}  {'f_pi':>8s}  {'error':>8s}")
print("  " + "-" * 26)
for g10 in range(1, 21):
    g = g10 / 10.0

    def M_scan(k2, gv=g):
        return M_Q * (Lambda_chi_dfc**2 / (k2 + Lambda_chi_dfc**2))**gv

    def dM_scan(k2, gv=g):
        return (M_Q * gv * Lambda_chi_dfc**(2*gv)
                * (-1.0) * (k2 + Lambda_chi_dfc**2)**(-(gv+1)))

    f2_scan = ps_running(M_scan, dM_scan, LAMBDA_UV)
    fpi_scan = math.sqrt(max(f2_scan, 0))
    err_scan = (fpi_scan / F_PI_OBS - 1) * 100
    marker = ""
    if abs(g - gamma_dfc) < 0.05:
        marker = " <-- DFC (6/11)"
    elif abs(g - gamma_qcd_nf3) < 0.05:
        marker = " <-- QCD N_f=3"
    print(f"  {g:>6.2f}  {fpi_scan:>7.2f}  {err_scan:>+7.1f}%{marker}")

print()

# Find exact gamma for f_pi = 92.07
g_lo, g_hi = 0.1, 2.0
for _ in range(60):
    g_mid = (g_lo + g_hi) / 2.0

    def M_bisect(k2, gv=g_mid):
        return M_Q * (Lambda_chi_dfc**2 / (k2 + Lambda_chi_dfc**2))**gv

    def dM_bisect(k2, gv=g_mid):
        return (M_Q * gv * Lambda_chi_dfc**(2*gv)
                * (-1.0) * (k2 + Lambda_chi_dfc**2)**(-(gv+1)))

    f2_bisect = ps_running(M_bisect, dM_bisect, LAMBDA_UV)
    fpi_bisect = math.sqrt(max(f2_bisect, 0))
    if fpi_bisect < F_PI_OBS:
        g_hi = g_mid
    else:
        g_lo = g_mid

gamma_exact = (g_lo + g_hi) / 2.0
print(f"  Exact γ for f_pi = 92.07: γ = {gamma_exact:.4f}")
print(f"  DFC γ = 6/11 = {gamma_dfc:.4f} ({(gamma_dfc/gamma_exact-1)*100:+.1f}% from exact)")
print()

# Find exact gamma for f_pi = 96.5 (binding threshold)
g_lo, g_hi = 0.01, 2.0
for _ in range(60):
    g_mid = (g_lo + g_hi) / 2.0

    def M_bisect2(k2, gv=g_mid):
        return M_Q * (Lambda_chi_dfc**2 / (k2 + Lambda_chi_dfc**2))**gv

    def dM_bisect2(k2, gv=g_mid):
        return (M_Q * gv * Lambda_chi_dfc**(2*gv)
                * (-1.0) * (k2 + Lambda_chi_dfc**2)**(-(gv+1)))

    f2_b2 = ps_running(M_bisect2, dM_bisect2, LAMBDA_UV)
    fpi_b2 = math.sqrt(max(f2_b2, 0))
    if fpi_b2 < F_PI_THRESHOLD:
        g_hi = g_mid
    else:
        g_lo = g_mid

gamma_threshold = (g_lo + g_hi) / 2.0
print(f"  Exact γ for f_pi = {F_PI_THRESHOLD} (binding): γ = {gamma_threshold:.4f}")
print(f"  DFC γ = {gamma_dfc:.4f}: {'BELOW threshold (binds)' if gamma_dfc > gamma_threshold else 'ABOVE threshold (does not bind)'}")
print()

check("D1: DFC γ = 6/11 produces binding",
      gamma_dfc > gamma_threshold)
print()


# =============================================================================
# Part E: Assessment
# =============================================================================
print("=" * 72)
print("Part E: Assessment")
print("=" * 72)
print()

print("SUMMARY OF f_pi PREDICTIONS (all 0 free parameters):")
print()
print(f"  {'Method':<50s}  {'f_pi':>8s}  {'error':>8s}")
print("  " + "-" * 70)
print(f"  {'Λ/π (dimensional estimate)':<50s}  {F_PI_DFC:>7.2f}  {(F_PI_DFC/F_PI_OBS-1)*100:>+7.1f}%")
print(f"  {'PS constant M_q (C387)':<50s}  {fpi_const:>7.2f}  {(fpi_const/F_PI_OBS-1)*100:>+7.1f}%")
print(f"  {'PS + running mass γ=6/11 (this module)':<50s}  {fpi_dfc_running:>7.2f}  {err_dfc:>+7.1f}%")
print(f"  {'Observed':<50s}  {F_PI_OBS:>7.2f}  {'---':>8s}")
print()

print(f"  Binding threshold: f_pi < {F_PI_THRESHOLD:.1f} MeV")
if fpi_dfc_running < F_PI_THRESHOLD:
    print(f"  DFC running-mass prediction BELOW threshold: DEUTERON BINDS")
else:
    print(f"  DFC running-mass prediction ABOVE threshold by "
          f"{fpi_dfc_running - F_PI_THRESHOLD:.1f} MeV")
print()

print("TIER ASSIGNMENTS:")
print(f"  PS constant-mass f_pi = {fpi_const:.2f}: T3 (C387)")
print(f"  PS running-mass f_pi = {fpi_dfc_running:.2f}: T3 (γ from b₀, not fitted)")
print(f"  Running mass enhancement: T3 (one-loop anomalous dimension)")
print()

check("E1: running mass improves over both Λ/π and constant PS",
      (abs(fpi_dfc_running/F_PI_OBS - 1)
       < min(abs(F_PI_DFC/F_PI_OBS - 1), abs(fpi_const/F_PI_OBS - 1))))

print()

# =============================================================================
# Summary
# =============================================================================
print("=" * 72)
print("SUMMARY")
print("=" * 72)
print()
print(f"  Total assertions: {n_assert}")
print(f"  PASS: {n_pass}")
print(f"  FAIL: {n_fail}")
print()
if n_fail == 0:
    print("  ALL ASSERTIONS PASSED")
else:
    print(f"  {n_fail} ASSERTION(S) FAILED")
